-d H:\git\Pmod\Sipeed_POMD_DTx2\POMD_DTx2\impl\gwsynthesis\POMD_DTx2.vg
-p GW5A-25B-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst H:\git\Pmod\Sipeed_POMD_DTx2\POMD_DTx2\src\top.cst
-cfg H:\git\Pmod\Sipeed_POMD_DTx2\POMD_DTx2\impl\pnr\device.cfg
-sdc H:\git\Pmod\Sipeed_POMD_DTx2\POMD_DTx2\src\top.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
